/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package DBPlayground

import DBPlayground.jdbc.DB
import spock.lang.Specification

class DBTestInsert extends Specification {
    def "application has a greeting"() {

    }
}
